name: ci-test

on:
  push:
    branches: [ main ]
  pull-request:
    branches: [ main ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-versions: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test